pipeline {

    agent any

    environment {
         PRISMA_API_URL =   'https://api.prismacloud.io'
         ACCESS_KEY     =   credentials ('pc-access-key')
         SECRET_KEY     =   credentials ('pc-secret-key')
    }

    stages {
        stage ('Checkov') {
            steps {
                script {
                    docker.image('bridgecrew/checkov:latest').inside("--entrypoint=''") {
                        sh 'checkov -d . -o cli -o junitxml --output-file-path console,results.xml --prisma-api-url ${PRISMA_API_URL} --bc-api-key ${ACCESS_KEY}::${SECRET_KEY} --repo-id irgarcia21/checkov-test --branch master'
                    }
                } 
            }
        }
        stage ('Deploy') {
            steps {
                script {
                    sh "echo 'deploy'"
                }
            }
            
        }
    }
}