pipeline {
    agent any
    environment {
         PRISMA_API_URL =   'https://api.prismacloud.io'
         ACCESS_KEY     =   credentials ('pc-access-key')
         SECRET_KEY     =   credentials ('pc-secret-key')
    }
    stages {
        stage ('checkov scan') {
            steps {
                script {
                    docker.image('bridgecrew/checkov:latest').inside("--entrypoint=''") {
                        unstash 'source'
                        try {
                            sh 'checkov -d . --use-enforcement-rules -o cli -o junitxml --output-file-path console,results.xml --bc-api-key ${ACCESS_KEY}::${SECRET_KEY} --repo-id  irgarcia21/checkov-tests --branch master'
                            junit skipPublishingChecks: true, testResults: 'results.xml'
                        } catch (err) {
                            junit skipPublishingChecks: true, testResults: 'results.xml'
                            throw err
                        }        
                    }
                }
            }
        }
        stage ('Deploy') {
            steps {
                script {
                    sh "echo 'deploy'"
                }
            }
            
        }
    }
}